Fix Cannot find implementation or library stub
I would sometimes get this locally when only modifying a test file and committing.

mypy.....................................................................Failed
- hook id: mypy
- exit code: 1

tests/test_linkotron.py:8: error: Cannot find implementation or library stub
for module named "linkotron"  [import]
    import linkotron
    ^
tests/test_linkotron.py:8: note: See https://mypy.readthedocs.io/en/stable/running_mypy.html#missing-imports
Found 1 error in 1 file (checked 1 source file)

It happens because pre-commit only passes the single modified file, so mypy doesn't
know about all the other source files.

Instead, have mypy run on all the source files so it takes the holistic view.